/**
 * Control flow object inlining pass.
 *
 * Detects "control flow storage objects" generated by javascript-obfuscator:
 * const/var declarations with object literals whose properties are binary/logical
 * proxy functions, call delegation functions, or string literals. Inlines all
 * call sites and member accesses, then removes the storage object.
 *
 * Also handles the "transformObjectKeys" pattern where properties are assigned
 * sequentially after an empty object declaration.
 */

import { traverse, t } from "../babel.js";
import type { File } from "@babel/types";
import type { ASTPass } from "../types.js";
import type { NodePath } from "@babel/traverse";

type PropertyInfo =
  | { type: "string"; value: string }
  | { type: "binary"; operator: t.BinaryExpression["operator"]; leftIdx: number; rightIdx: number }
  | { type: "logical"; operator: t.LogicalExpression["operator"]; leftIdx: number; rightIdx: number }
  | { type: "call"; calleeIdx: number; argIndices: number[]; hasRest: boolean };

export const controlFlowObjectPass: ASTPass = {
  name: "control-flow-object",
  description: "Inline control flow storage objects (proxy functions, string literals)",

  run(ast: File): File {
    mergeSequentialAssignments(ast);

    let changed = true;
    while (changed) {
      changed = false;
      traverse(ast, {
        VariableDeclaration(path) {
          if (inlineControlFlowObject(path)) {
            changed = true;
          }
        },
      });
    }

    return ast;
  },
};

function inlineControlFlowObject(path: NodePath<t.VariableDeclaration>): boolean {
  if (path.node.declarations.length !== 1) return false;
  const decl = path.node.declarations[0];
  if (!t.isIdentifier(decl.id) || !t.isObjectExpression(decl.init)) return false;

  const objName = decl.id.name;

  path.scope.crawl();
  const binding = path.scope.getBinding(objName);
  if (!binding) return false;

  // Safety: no reassignment of the variable itself
  if (binding.constantViolations.length > 0) return false;

  // Safety: all references must be member accesses (no aliasing via passing as argument etc.)
  if (!allRefsAreMemberAccess(binding)) return false;

  // Safety: no property writes (obj.key = ...)
  if (hasPropertyWrites(binding)) return false;

  // Analyze all properties — returns null if any property doesn't match a known proxy/string pattern
  const propMap = analyzeProperties(decl.init);
  if (!propMap || propMap.size === 0) return false;

  let inlinedAny = false;

  // Phase 1: Inline string literal references (not in callee position)
  for (const ref of [...binding.referencePaths]) {
    const memberPath = ref.parentPath;
    if (!memberPath || !t.isMemberExpression(memberPath.node)) continue;

    const propName = getMemberPropertyName(memberPath.node);
    if (!propName) continue;
    const info = propMap.get(propName);
    if (!info || info.type !== "string") continue;

    // Skip if this member expression is the callee of a call
    if (t.isCallExpression(memberPath.parent) && memberPath.parent.callee === memberPath.node) continue;

    memberPath.replaceWith(t.stringLiteral(info.value));
    inlinedAny = true;
  }

  // Phase 2: Inline function proxy calls
  for (const ref of [...binding.referencePaths]) {
    const memberPath = ref.parentPath;
    if (!memberPath || !t.isMemberExpression(memberPath.node)) continue;

    const propName = getMemberPropertyName(memberPath.node);
    if (!propName) continue;
    const info = propMap.get(propName);
    if (!info || info.type === "string") continue;

    const callPath = memberPath.parentPath;
    if (!callPath || !t.isCallExpression(callPath.node)) continue;
    if (callPath.node.callee !== memberPath.node) continue;

    const args = callPath.node.arguments as t.Expression[];

    if (info.type === "binary") {
      callPath.replaceWith(
        t.binaryExpression(info.operator, t.cloneNode(args[info.leftIdx]), t.cloneNode(args[info.rightIdx]))
      );
      inlinedAny = true;
    } else if (info.type === "logical") {
      callPath.replaceWith(
        t.logicalExpression(info.operator, t.cloneNode(args[info.leftIdx]), t.cloneNode(args[info.rightIdx]))
      );
      inlinedAny = true;
    } else if (info.type === "call") {
      const callee = t.cloneNode(args[info.calleeIdx]);
      let passedArgs: t.Expression[];
      if (info.hasRest) {
        passedArgs = args.slice(info.calleeIdx + 1).map(a => t.cloneNode(a));
      } else {
        passedArgs = info.argIndices.map(i => t.cloneNode(args[i]));
      }
      callPath.replaceWith(t.callExpression(callee, passedArgs));
      inlinedAny = true;
    }
  }

  // Phase 3: Remove the declaration if no references remain
  if (inlinedAny) {
    path.scope.crawl();
    const updatedBinding = path.scope.getBinding(objName);
    if (!updatedBinding || updatedBinding.referencePaths.length === 0) {
      path.remove();
    }
  }

  return inlinedAny;
}

/** Merge `_0x["key"] = value` assignments after `var _0x = {}` into the object literal. */
function mergeSequentialAssignments(ast: File): void {
  traverse(ast, {
    VariableDeclaration(path) {
      if (path.node.declarations.length !== 1) return;
      const decl = path.node.declarations[0];
      if (!t.isIdentifier(decl.id) || !t.isObjectExpression(decl.init)) return;
      if (decl.init.properties.length !== 0) return;

      const objName = decl.id.name;
      const objExpr = decl.init;
      const siblings = path.getAllNextSiblings();
      const toRemove: NodePath[] = [];

      for (const sib of siblings) {
        if (!t.isExpressionStatement(sib.node)) break;
        const expr = sib.node.expression;
        if (!t.isAssignmentExpression(expr) || expr.operator !== "=") break;

        const left = expr.left;
        if (!t.isMemberExpression(left)) break;
        if (!t.isIdentifier(left.object) || left.object.name !== objName) break;

        let propName: string | null = null;
        if (t.isStringLiteral(left.property) && left.computed) {
          propName = left.property.value;
        } else if (t.isIdentifier(left.property) && !left.computed) {
          propName = left.property.name;
        }
        if (!propName) break;

        objExpr.properties.push(t.objectProperty(t.identifier(propName), expr.right));
        toRemove.push(sib);
      }

      for (const sib of toRemove) {
        sib.remove();
      }
    },
  });
}

function analyzeProperties(obj: t.ObjectExpression): Map<string, PropertyInfo> | null {
  const map = new Map<string, PropertyInfo>();

  for (const prop of obj.properties) {
    if (t.isSpreadElement(prop) || !t.isObjectProperty(prop)) return null;

    let key: string;
    if (t.isIdentifier(prop.key)) {
      key = prop.key.name;
    } else if (t.isStringLiteral(prop.key)) {
      key = prop.key.value;
    } else {
      return null;
    }

    const value = prop.value;
    if (t.isStringLiteral(value)) {
      map.set(key, { type: "string", value: value.value });
      continue;
    }

    if (t.isFunctionExpression(value)) {
      const info = analyzeFunctionProxy(value);
      if (!info) return null;
      map.set(key, info);
      continue;
    }

    return null;
  }

  return map;
}

function analyzeFunctionProxy(fn: t.FunctionExpression): PropertyInfo | null {
  if (fn.body.body.length !== 1) return null;

  const stmt = fn.body.body[0];
  if (!t.isReturnStatement(stmt) || !stmt.argument) return null;

  const ret = stmt.argument;
  const paramNames: string[] = [];
  let hasRest = false;

  for (const p of fn.params) {
    if (t.isIdentifier(p)) {
      paramNames.push(p.name);
    } else if (t.isRestElement(p) && t.isIdentifier(p.argument)) {
      paramNames.push(p.argument.name);
      hasRest = true;
    } else {
      return null;
    }
  }

  if (t.isBinaryExpression(ret)) {
    if (!t.isIdentifier(ret.left) || !t.isIdentifier(ret.right)) return null;
    const leftIdx = paramNames.indexOf(ret.left.name);
    const rightIdx = paramNames.indexOf(ret.right.name);
    if (leftIdx === -1 || rightIdx === -1) return null;
    return { type: "binary", operator: ret.operator, leftIdx, rightIdx };
  }

  if (t.isLogicalExpression(ret)) {
    if (!t.isIdentifier(ret.left) || !t.isIdentifier(ret.right)) return null;
    const leftIdx = paramNames.indexOf(ret.left.name);
    const rightIdx = paramNames.indexOf(ret.right.name);
    if (leftIdx === -1 || rightIdx === -1) return null;
    return { type: "logical", operator: ret.operator, leftIdx, rightIdx };
  }

  if (t.isCallExpression(ret)) {
    if (!t.isIdentifier(ret.callee)) return null;
    const calleeIdx = paramNames.indexOf(ret.callee.name);
    if (calleeIdx === -1) return null;

    if (hasRest) {
      if (ret.arguments.length !== 1) return null;
      const arg = ret.arguments[0];
      if (!t.isSpreadElement(arg) || !t.isIdentifier(arg.argument)) return null;
      if (paramNames.indexOf(arg.argument.name) === -1) return null;
      return { type: "call", calleeIdx, argIndices: [], hasRest: true };
    }

    const argIndices: number[] = [];
    for (const a of ret.arguments) {
      if (t.isSpreadElement(a) || !t.isIdentifier(a)) return null;
      const idx = paramNames.indexOf(a.name);
      if (idx === -1) return null;
      argIndices.push(idx);
    }
    return { type: "call", calleeIdx, argIndices, hasRest: false };
  }

  return null;
}

function getMemberPropertyName(node: t.MemberExpression): string | null {
  if (!node.computed && t.isIdentifier(node.property)) return node.property.name;
  if (node.computed && t.isStringLiteral(node.property)) return node.property.value;
  return null;
}

function allRefsAreMemberAccess(binding: { referencePaths: readonly NodePath[] }): boolean {
  for (const ref of binding.referencePaths) {
    if (!t.isMemberExpression(ref.parent) || (ref.parent as t.MemberExpression).object !== ref.node) {
      return false;
    }
  }
  return true;
}

function hasPropertyWrites(binding: { referencePaths: readonly NodePath[] }): boolean {
  for (const ref of binding.referencePaths) {
    const memberPath = ref.parentPath;
    if (!memberPath) continue;
    if (
      t.isAssignmentExpression(memberPath.parent) &&
      (memberPath.parent as t.AssignmentExpression).left === memberPath.node
    ) {
      return true;
    }
  }
  return false;
}
